# Generated by Django 4.0.3 on 2022-03-02 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('max_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[a-zA-Z\\s]*$', 'Only alphabets characters are allowed.')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+[a-zA-Z\\s]*$', 'Only alphabets characters are allowed.')])),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='school.schools')),
            ],
        ),
    ]
